### ISSUE TITLE
bodies disappear in TTT

### ISSUE THREAD

**Issue by mckennapsean** [DougTy/gibmod#12]
I have confirmed that the code in commit a07f815 (most recent) causes bodies to disappear on our server running TTT with gibmod. After death, they just disappear, which makes it a problem when the evidence disappears and no one can ID bodies.

Rolling back one commit, everything works as expected. I haven't tested reverting individual changes, but I can do so if requested. Thank you.

**Comment by DougTy** [comment]
Fixed in 04ee388
Thanks for investigating!
